baseURL = 'https://nurazon59.github.io/aip-ja/'
defaultContentLanguage = 'ja'
defaultContentLanguageInSubdir = true
title = 'AIP JA'

[languages]
  [languages.en]
  contentDir = 'content/en'
  languageName = 'English'
  locale = 'en-US'
  weight = 1

  [languages.ja]
  contentDir = 'content/ja'
  languageName = '日本語'
  locale = 'ja-JP'
  weight = 2
