baseURL = 'https://nurazon59.github.io/aip-ja/'
defaultContentLanguage = 'ja'
defaultContentLanguageInSubdir = true
title = 'AIP JA'
theme = 'hugo-book'

[languages]
[languages.en]
contentDir = 'content/en'
label = 'English'
locale = 'en-US'
weight = 1

[languages.ja]
contentDir = 'content/ja'
label = '日本語'
locale = 'ja-JP'
weight = 2

[params]
BookSection = 'aip'
BookComments = false
custom_css = ['/css/custom.css']

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
